server:
  servlet:
    encoding:
      force-response: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc: # swagger 오류로 인해 추가
    pathmatch:
      matching-strategy: ant_path_matcher
